CREATE TABLE CQRS_CPL_ORDER (
  ORDER_ID serial  PRIMARY KEY,
  USER_ID int8 ,
  CONTENT varchar(45) ,
  PAYMENT_ID int8 ,
  VERSION int8 ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP  ,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE CQRS_CPL_PAYMENT (
  PAYMENT_ID serial PRIMARY KEY,
  AMOUNT decimal(10,0) ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP ,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE CQRS_CPL_SEAT_AVAILABILITY (
  SEAT_AVAILABILITY_ID serial PRIMARY KEY,
  ORDER_ID int8 ,
  USER_ID int8 ,
  QUANTITY decimal(10,0) ,
  PAYMENT_ID int8 ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;
