CREATE TABLE CQRS_QCK_ORDER (
  ORDER_ID serial  PRIMARY KEY,
  STATUS_ID int8 ,
  MERCHANT_ORDER_NO varchar(45) ,
  PAYMENT_ID int8 ,
  VERSION_ID int8 ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP  ,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE CQRS_QCK_PAYMENT (
  PAYMENT_ID serial PRIMARY KEY,
  TOTAL_AMOUNT decimal(10,0) ,
	PAYMENT_NO varchar(45) ,
	STATUS_ID int8 ,
	ORDER_ID int8 ,
	VERSION int8 ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP ,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;

CREATE TABLE CQRS_QCK_ORDER_LINE (
  ORDER_LINE_ID serial PRIMARY KEY,
  PRODUCT_ID int8 ,
  PRICE int8 ,
  ORDER_ID int8 ,
  CREATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATE_TIME timestamp(6) DEFAULT CURRENT_TIMESTAMP
) ;
